name: Android AAR

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build Android AAR
        run: |
          chmod +x ./gradlew
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            ./gradlew :vectora-search:assembleRelease -PVERSION_NAME=$VERSION
          else
            ./gradlew :vectora-search:assembleRelease
          fi

      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: vectora-search-aar
          path: vectora-search/build/outputs/aar/*.aar
